# Generated by Django 2.2.7 on 2019-11-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interestingReads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookModel',
            new_name='Book',
        ),
    ]
